### ISSUE TITLE
[1.12.2] Craft Studio Crashes While Loading Forge (1/7)

### ISSUE THREAD

**Issue by PulseBeat02** [Leviathan-Studio/CraftStudioAPI#41] opened 2018-09-03 00:50 UTC
## Expected Behavior

I expected the mod to load normally in the forge loading screen in phase 1/7.

## Current Behavior

What happens instead is that Forge crashes instead of loading to the Minecraft title screen.

## Possible Solution

I am not an java or mod expert, but it could be another mod that is interfering or conflicting with this mod. Removal of this mod may result in a fix, but I do not know what that mod is.

## Context

The issue prevented me from loading my 500+ modpack.

## Crash Report

Crash Report: https://paste.dimdev.org/ozofemuqoz.mccrash

(Is it fine if I use hastebin? It is a similar website like pastebin.

## Your Environment

The error happened in 1.12.2 Forge while loading in Phase 1/7

Craft Studio Version: 1.0.0.93-mc1.12-alpha
Forge Version: 14.23.4.2759
My project isn't open source, however, the crash report should provide enough information for all the mods loaded and errors.

Other Notes: I was installing the mod Animania but it requires this mod here.

**Comment by Timmypote** [comment] 2018-09-03 10:38
Duplicate of #38
Please search for your crash before creating an issue :)

**Closed by Timmypote** 2018-09-03 10:38 UTC
