### ISSUE TITLE
Crash when adding the Decocraft mod

### ISSUE THREAD

**Issue by Lucky7s** [Leviathan-Studio/CraftStudioAPI#42] opened 2018-09-06 12:16 UTC
Using Craftstudio to run the Animania mod on a 1.12.2 Modpack, After adding the Decocraft2 mod the pack crashes. Is there an incompatibility with Decocraft?
[crash-2018-09-03_05.01.31-client.txt](https://github.com/Leviathan-Studio/CraftStudioAPI/files/2356964/crash-2018-09-03_05.01.31-client.txt)

**Comment by Phenix246** [comment] 2018-09-06 13:43
Duplicate of #38 I think

Check the answer given by Timmypote https://github.com/Leviathan-Studio/CraftStudioAPI/issues/38#issuecomment-396060826

**Closed** 2018-09-06 14:32 UTC
